# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               while(1);
tagline:             'Computational Matters'
description:         'Computational Matters'
url:                 http://codermahesh.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ybar
  url:               http://doesnotexit.com
  email:             doesnotexist@gmail.com

# Custom vars
version:             1.0.0
