# Dependencies
markdown:            kramdown
highlighter:         pygments
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               while(1);
tagline:             'Computational Matters'
description:         'Computational Matters'
url:                 http://codermahesh.github.io
baseurl:             /
paginate:            3

# About/contact
author:
  name:              ybar
  url:               http://doesnotexist.com
  email:             doesnotexist@gmail.com

# Custom vars
version:             1.0.0


# Paginate

paginate: 3
#paginate_path: "/page:num/"
